### ISSUE TITLE
Remove Delaunay & Meshing

### ISSUE THREAD

**Issue by jhkolb** [jhkolb/sparkRocks#32]
We can use simplex integration instead of Delaunay triangulation when we calculate centroids.

This will simplify our code base quite a bit.

**Comment by shellshocked2003** [comment]
Okay, so it's possible to do this. Simplex integration requires oriented vertices, so some of the calculations from `BlockVTK` would need to be moved into `Block` - specifically `ccwCompare` and `orientVertices`. Once the vertices are oriented, finding the volume and centroid using simplex integration is pretty straightforward. Should I go ahead and change this?

**Comment by jhkolb** [comment]
I see. And most of these calculations would become `private` utility methods, right? It seems to me that we wouldn't have to change the external interface of `Block` at all, just some aspects of the internal implementation.

Personally I would like to use the simplex integration approach, but I'll defer to your judgment if you think there are good reasons not to do this.

**Comment by shellshocked2003** [comment]
Okay. I think using simplex integration is better since it also allows for more continuity between `Block` and `BlockVTK`. We'll also eliminate the need to use `Delaunay`, which I haven't had the heart to clean up...

Yeah, we wouldn't have to change the external interface of `Block` at all. All the changes will be internal. `BlockVTK` will change a bit too, but that's relatively minor compared to having to overhaul `Block`. Not sure, but this might also get rid of the unit test pains for `BlockVTK`. We'll see.

I'll try to knock this out this week.

**Comment by jhkolb** [comment]
Resolved in #40.
