### ISSUE TITLE
Add visualization 

### ISSUE THREAD

**Issue by shellshocked2003** [jhkolb/sparkRocks#6]
Visualize results:
- Output results in vtk format to that they can be visualized in ParaView

**Comment by jhkolb** [comment]
The VTK Java wrappers are a huge pain to set up. I propose that instead of producing VTK files from within our code, we just use Python to convert the JSON produced by our current implementation into a VTK file.

The VTK Wiki has an article with helpful links here: http://www.vtk.org/Wiki/VTK/Writing_VTK_files_using_python

**Comment by shellshocked2003** [comment]
See pull request #16
